input_data:
  input_folder: input_data
  input_file: points-of-interest-newport-csv.csv

api_call_variables:
  call_api: True
  city_name: Newport
  arrival_time_period: weekday_morning
  travel_time: 3600

output_data:
  output_folder: output_data
  h5_file: results.h5
  output_file: results.xlsx
  store_h5: True
  write_to_excel: True

